Import necessary library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.datasets import make_regression
X ,y =make_regression(n_samples=2000,random_state=1)

In [3]:
X

array([[ 1.24656308, -0.00262717,  1.16177117, ..., -0.14381404,
         1.04897789,  0.36642707],
       [ 1.98789962, -0.74289827,  0.46392306, ..., -0.07953001,
         0.88431814, -0.12744446],
       [-1.18110317, -0.4599301 ,  1.07125243, ...,  0.41026575,
         0.75133724,  0.39310924],
       ...,
       [ 0.10949255, -0.93311559,  1.06941626, ..., -0.15958241,
        -1.09792226,  0.16945106],
       [-0.59682953,  0.91196902,  0.32905821, ..., -0.49513463,
         1.30232475, -0.67180649],
       [ 0.88513231, -0.95744249,  1.24415716, ..., -0.03960346,
        -0.44315668,  1.04897287]])

In [4]:
y

array([-244.6379103 ,  338.19201455, -369.33489019, ...,   89.84615892,
         40.23247176, -113.19250449])

In [5]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X,y,test_size=0.3,random_state=12)

In [6]:
X_train

array([[-0.3102569 , -0.35427619,  0.39650492, ...,  1.26959618,
        -0.30150675, -2.26888313],
       [ 1.28044403,  1.73871889,  0.84672379, ..., -0.51392111,
        -1.44702872, -1.61237671],
       [ 0.58455701, -0.18854658,  0.10667214, ...,  0.3039744 ,
        -0.61025316, -1.2003673 ],
       ...,
       [-0.87636515,  2.1606535 ,  0.69440495, ...,  0.68105216,
         0.4741391 , -1.15527546],
       [ 0.8521572 , -0.50782106, -0.47473822, ..., -2.60530035,
         1.69787155, -0.57837416],
       [-0.92166369,  1.42898437,  0.15152283, ...,  1.97076816,
        -2.0457776 , -0.01832535]])

In [7]:
X_test

array([[-2.47913336e+00, -1.32941774e+00,  7.55895123e-01, ...,
         4.32523466e-01,  6.55392088e-01, -4.89171664e-01],
       [ 1.21935522e+00,  9.17253872e-01, -6.24653153e-02, ...,
         6.51603617e-01,  3.19617561e-02,  5.35192360e-01],
       [ 1.59296974e+00,  1.29511140e-01,  3.47589377e-01, ...,
         1.87142477e-01,  3.10548285e-02,  9.68582688e-01],
       ...,
       [-1.62038450e-01,  7.36388470e-01,  1.29887994e+00, ...,
         1.34411245e+00,  9.42955805e-01,  6.33662061e-01],
       [-1.37604633e-03,  7.85995759e-01,  8.75557342e-02, ...,
         7.93833204e-01, -2.16655900e+00, -1.92740972e+00],
       [ 1.92506088e+00,  1.44194971e+00,  1.00439787e+00, ...,
         4.27048308e-01,  2.08982884e-01, -1.65906685e-01]])

In [8]:
from sklearn.ensemble import GradientBoostingRegressor
classifier =GradientBoostingRegressor()
classifier.fit(X_train ,y_train)
y_pred =classifier.predict(X_test)
y_pred

array([ -22.1290602 , -226.7267504 ,  339.30098721, -250.20728021,
        238.30173024,  108.6804042 ,   73.37829821,   26.8231191 ,
        -97.24683224,  313.17744028,  -89.09907451,  -69.37138288,
        123.70935971,   97.9940697 ,  -50.49253232,  126.47769919,
        189.81565494,  -51.40178067, -133.87550502, -175.82217267,
         49.98503842,  258.55140609,   69.04543483,   40.93138933,
         26.08587494,  182.60616829,    6.597482  ,   60.43696854,
         78.14234166, -248.50406189, -113.53846718,  136.12118034,
         29.20165152,  457.98854723,   27.40361964,  -70.57610957,
        153.89595423,   83.04926804,   -2.86097509, -143.70893026,
        239.2676661 ,   44.35904471, -144.84358589,  145.13122947,
        134.81992734,   80.6929683 ,  198.4587239 ,  -57.83149989,
         32.08204372,  171.69235126,  394.81257709,  -81.5776387 ,
        -11.53740756, -150.27714772,  -62.29441293,  248.12937775,
       -150.30888948, -200.0285949 ,  101.01231641,  -58.61959

In [9]:
from sklearn.metrics import r2_score
print(r2_score(y_test ,y_pred))

0.9148991376273925


hyperparameter tunning

In [10]:
from sklearn.model_selection import GridSearchCV
param_grid ={"n_estimators":[100,150],
            "learning_rate":[0.001,0.1,1],
            "loss":["squared_error","absolute_error"]}
grad =GradientBoostingRegressor()

In [11]:
clf =GridSearchCV(estimator=grad ,param_grid=param_grid ,cv =5,verbose=3)

In [12]:
clf.fit(X_train ,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.078 total time=   4.8s
[CV 2/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.075 total time=   4.7s
[CV 3/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.075 total time=   4.7s
[CV 4/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.063 total time=   4.7s
[CV 5/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.073 total time=   4.7s
[CV 1/5] END learning_rate=0.001, loss=squared_error, n_estimators=150;, score=0.112 total time=   7.2s
[CV 2/5] END learning_rate=0.001, loss=squared_error, n_estimators=150;, score=0.107 total time=   7.3s
[CV 3/5] END learning_rate=0.001, loss=squared_error, n_estimators=150;, score=0.111 total time=   7.2s
[CV 4/5] END learning_rate=0.001, loss=squared_error, n_estimators=150;, score=0.095 total time=   7.2s
[CV

GridSearchCV(cv=5, estimator=GradientBoostingRegressor(),
             param_grid={'learning_rate': [0.001, 0.1, 1],
                         'loss': ['squared_error', 'absolute_error'],
                         'n_estimators': [100, 150]},
             verbose=3)

In [15]:
clf.best_estimator_

GradientBoostingRegressor(n_estimators=150)

In [16]:
clf.best_score_

0.9335989605522264